build:
  type: build
  tags:
    - htpc
  script:
    - ./configure.sh
    - cd build
    - make -j
  cache:
    policy: push
    paths:
      - build/

test:
  type: test
  tags:
    - htpc
  script:
    - cd build/tests
    - ./LazyTest -p
  dependencies:
    - build
  cache:
    policy: pull
    paths:
      - build/
